version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    # volumes:
    #   - /home/user/Desktop:/var/lib/postgresql/data
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      default:
        ipv4_address: 172.16.1.9

  fastapi:
    container_name: fastapi_CRUD
    build:
      context: .
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 172.16.1.8

networks:
  default:
      driver: bridge
      ipam:
        config:
          - subnet: 172.16.1.0/24